version: '3'

services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - database
  database:
    container_name: database
    image: mongo:latest
    ports:
      - '27017:27017'